# Generated by Django 5.0.1 on 2024-01-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_menucategory_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetail",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
