# Generated by Django 5.0.1 on 2024-01-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_blogdetail_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=120, null=True)),
                ("subject", models.CharField(blank=True, max_length=120, null=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
